### ISSUE TITLE
Big Problem

### ISSUE THREAD

**Issue by jojoGIF2001** [Flo3103/Minecraft_Quiz#1]
I have tryed to play your game which looks realy cool but when i try to click a Button nothing happens.

and what is a "Wamperzwicker" and a "Körperzwicker", "Gschdocher"?

**Comment by Flo3103** [comment]
Sry for the big Problems but i think you dont click right so pleas restart
the App and try again.


Send from The Basis Server


Johannes Dietrich ***@***.***> schrieb am Di., 7. Juni 2022,
20:35:
